// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: pb/metamorphosis.proto

package pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type LogEntry struct {
	Offset uint64 `protobuf:"varint,1,opt,name=Offset,proto3" json:"Offset,omitempty"`
	Key    []byte `protobuf:"bytes,2,opt,name=Key,proto3" json:"Key,omitempty"`
	Value  []byte `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	// This int enable metamorphosis to create a
	// unique context to wait for in the commit replay.
	// This way append can wait for changes to be committed.
	Context uint64 `protobuf:"varint,4,opt,name=Context,proto3" json:"Context,omitempty"`
	// Indicates whether this bool is an entry intent or not.
	IsIntent bool `protobuf:"varint,5,opt,name=IsIntent,proto3" json:"IsIntent,omitempty"`
}

func (m *LogEntry) Reset()                    { *m = LogEntry{} }
func (m *LogEntry) String() string            { return proto.CompactTextString(m) }
func (*LogEntry) ProtoMessage()               {}
func (*LogEntry) Descriptor() ([]byte, []int) { return fileDescriptorMetamorphosis, []int{0} }

type MetamorphosisLog struct {
	// this map will contain keys and values from the log in compacted form
	State map[string][]byte `protobuf:"bytes,1,rep,name=state" json:"state,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// this will contain all log entries with the map as base state
	Log []*LogEntry `protobuf:"bytes,2,rep,name=log" json:"log,omitempty"`
	// offsets are computed by the position of an intent in the log
	// plus the base offset from previous compactions
	BaseOffset uint64 `protobuf:"varint,3,opt,name=baseOffset,proto3" json:"baseOffset,omitempty"`
}

func (m *MetamorphosisLog) Reset()                    { *m = MetamorphosisLog{} }
func (m *MetamorphosisLog) String() string            { return proto.CompactTextString(m) }
func (*MetamorphosisLog) ProtoMessage()               {}
func (*MetamorphosisLog) Descriptor() ([]byte, []int) { return fileDescriptorMetamorphosis, []int{1} }

func init() {
	proto.RegisterType((*LogEntry)(nil), "pb.LogEntry")
	proto.RegisterType((*MetamorphosisLog)(nil), "pb.MetamorphosisLog")
}
func (m *LogEntry) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LogEntry) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Offset != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintMetamorphosis(dAtA, i, uint64(m.Offset))
	}
	if len(m.Key) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintMetamorphosis(dAtA, i, uint64(len(m.Key)))
		i += copy(dAtA[i:], m.Key)
	}
	if len(m.Value) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintMetamorphosis(dAtA, i, uint64(len(m.Value)))
		i += copy(dAtA[i:], m.Value)
	}
	if m.Context != 0 {
		dAtA[i] = 0x20
		i++
		i = encodeVarintMetamorphosis(dAtA, i, uint64(m.Context))
	}
	if m.IsIntent {
		dAtA[i] = 0x28
		i++
		if m.IsIntent {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *MetamorphosisLog) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MetamorphosisLog) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.State) > 0 {
		for k, _ := range m.State {
			dAtA[i] = 0xa
			i++
			v := m.State[k]
			byteSize := 0
			if len(v) > 0 {
				byteSize = 1 + len(v) + sovMetamorphosis(uint64(len(v)))
			}
			mapSize := 1 + len(k) + sovMetamorphosis(uint64(len(k))) + byteSize
			i = encodeVarintMetamorphosis(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintMetamorphosis(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			if len(v) > 0 {
				dAtA[i] = 0x12
				i++
				i = encodeVarintMetamorphosis(dAtA, i, uint64(len(v)))
				i += copy(dAtA[i:], v)
			}
		}
	}
	if len(m.Log) > 0 {
		for _, msg := range m.Log {
			dAtA[i] = 0x12
			i++
			i = encodeVarintMetamorphosis(dAtA, i, uint64(msg.Size()))
			n, err := msg.MarshalTo(dAtA[i:])
			if err != nil {
				return 0, err
			}
			i += n
		}
	}
	if m.BaseOffset != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintMetamorphosis(dAtA, i, uint64(m.BaseOffset))
	}
	return i, nil
}

func encodeVarintMetamorphosis(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *LogEntry) Size() (n int) {
	var l int
	_ = l
	if m.Offset != 0 {
		n += 1 + sovMetamorphosis(uint64(m.Offset))
	}
	l = len(m.Key)
	if l > 0 {
		n += 1 + l + sovMetamorphosis(uint64(l))
	}
	l = len(m.Value)
	if l > 0 {
		n += 1 + l + sovMetamorphosis(uint64(l))
	}
	if m.Context != 0 {
		n += 1 + sovMetamorphosis(uint64(m.Context))
	}
	if m.IsIntent {
		n += 2
	}
	return n
}

func (m *MetamorphosisLog) Size() (n int) {
	var l int
	_ = l
	if len(m.State) > 0 {
		for k, v := range m.State {
			_ = k
			_ = v
			l = 0
			if len(v) > 0 {
				l = 1 + len(v) + sovMetamorphosis(uint64(len(v)))
			}
			mapEntrySize := 1 + len(k) + sovMetamorphosis(uint64(len(k))) + l
			n += mapEntrySize + 1 + sovMetamorphosis(uint64(mapEntrySize))
		}
	}
	if len(m.Log) > 0 {
		for _, e := range m.Log {
			l = e.Size()
			n += 1 + l + sovMetamorphosis(uint64(l))
		}
	}
	if m.BaseOffset != 0 {
		n += 1 + sovMetamorphosis(uint64(m.BaseOffset))
	}
	return n
}

func sovMetamorphosis(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozMetamorphosis(x uint64) (n int) {
	return sovMetamorphosis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *LogEntry) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetamorphosis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LogEntry: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LogEntry: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Offset", wireType)
			}
			m.Offset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Offset |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetamorphosis
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Key = append(m.Key[:0], dAtA[iNdEx:postIndex]...)
			if m.Key == nil {
				m.Key = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Value", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthMetamorphosis
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Value = append(m.Value[:0], dAtA[iNdEx:postIndex]...)
			if m.Value == nil {
				m.Value = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			m.Context = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Context |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsIntent", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsIntent = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipMetamorphosis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetamorphosis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MetamorphosisLog) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowMetamorphosis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MetamorphosisLog: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MetamorphosisLog: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetamorphosis
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.State == nil {
				m.State = make(map[string][]byte)
			}
			var mapkey string
			mapvalue := []byte{}
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowMetamorphosis
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetamorphosis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthMetamorphosis
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var mapbyteLen uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowMetamorphosis
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						mapbyteLen |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intMapbyteLen := int(mapbyteLen)
					if intMapbyteLen < 0 {
						return ErrInvalidLengthMetamorphosis
					}
					postbytesIndex := iNdEx + intMapbyteLen
					if postbytesIndex > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = make([]byte, mapbyteLen)
					copy(mapvalue, dAtA[iNdEx:postbytesIndex])
					iNdEx = postbytesIndex
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipMetamorphosis(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthMetamorphosis
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.State[mapkey] = mapvalue
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Log", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthMetamorphosis
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Log = append(m.Log, &LogEntry{})
			if err := m.Log[len(m.Log)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BaseOffset", wireType)
			}
			m.BaseOffset = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BaseOffset |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipMetamorphosis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthMetamorphosis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipMetamorphosis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowMetamorphosis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowMetamorphosis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthMetamorphosis
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowMetamorphosis
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipMetamorphosis(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthMetamorphosis = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowMetamorphosis   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("pb/metamorphosis.proto", fileDescriptorMetamorphosis) }

var fileDescriptorMetamorphosis = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcf, 0x4a, 0xf3, 0x40,
	0x14, 0xc5, 0x7b, 0x93, 0xa6, 0x5f, 0xbe, 0x6b, 0x17, 0x65, 0x08, 0x65, 0xc8, 0x62, 0x0c, 0x5d,
	0x65, 0x95, 0x82, 0x22, 0x14, 0x97, 0x8a, 0x8b, 0x62, 0x45, 0x18, 0xc1, 0x7d, 0x02, 0xd3, 0x28,
	0xb6, 0x99, 0x90, 0x19, 0xc5, 0xec, 0x7c, 0x37, 0x37, 0x5d, 0xf6, 0x11, 0x6c, 0x9e, 0x44, 0x66,
	0xa6, 0xd5, 0xe2, 0xee, 0xfe, 0xee, 0x3f, 0xce, 0x39, 0x38, 0xae, 0x8b, 0xe9, 0x5a, 0xe8, 0x7c,
	0x2d, 0x9b, 0xfa, 0x49, 0xaa, 0x67, 0x95, 0xd5, 0x8d, 0xd4, 0x92, 0x78, 0x75, 0x11, 0x47, 0xa5,
	0x2c, 0xa5, 0xc5, 0xa9, 0xa9, 0xdc, 0x64, 0xf2, 0x01, 0x18, 0x2e, 0x64, 0x79, 0x53, 0xe9, 0xa6,
	0x25, 0x63, 0x1c, 0xdc, 0x2f, 0x97, 0x4a, 0x68, 0x0a, 0x09, 0xa4, 0x7d, 0xbe, 0x27, 0x32, 0x42,
	0xff, 0x56, 0xb4, 0xd4, 0x4b, 0x20, 0x1d, 0x72, 0x53, 0x92, 0x08, 0x83, 0xc7, 0x7c, 0xf5, 0x2a,
	0xa8, 0x6f, 0x7b, 0x0e, 0x08, 0xc5, 0x7f, 0xd7, 0xb2, 0xd2, 0xe2, 0x5d, 0xd3, 0xbe, 0x7d, 0x70,
	0x40, 0x12, 0x63, 0x38, 0x57, 0xf3, 0x4a, 0x8b, 0x4a, 0xd3, 0x20, 0x81, 0x34, 0xe4, 0x3f, 0x3c,
	0xf9, 0x04, 0x1c, 0xdd, 0x1d, 0x8b, 0x5e, 0xc8, 0x92, 0x5c, 0x60, 0xa0, 0x74, 0xae, 0x05, 0x85,
	0xc4, 0x4f, 0x4f, 0xce, 0x4e, 0xb3, 0xba, 0xc8, 0xfe, 0x2e, 0x65, 0x0f, 0x66, 0xc3, 0x4a, 0xe7,
	0x6e, 0x9b, 0x30, 0xf4, 0x57, 0xb2, 0xa4, 0x9e, 0x3d, 0x1a, 0x9a, 0xa3, 0x83, 0x39, 0x6e, 0x06,
	0x84, 0x21, 0x16, 0xb9, 0x12, 0x7b, 0x97, 0xbe, 0x15, 0x79, 0xd4, 0x89, 0x67, 0x88, 0xbf, 0x4f,
	0x8d, 0xef, 0x17, 0xd1, 0xda, 0x30, 0xfe, 0x73, 0x53, 0x1a, 0xdf, 0x6f, 0xd6, 0xb7, 0xcb, 0xc2,
	0xc1, 0xa5, 0x37, 0x83, 0xab, 0x68, 0xb3, 0x63, 0xbd, 0xed, 0x8e, 0xf5, 0x36, 0x1d, 0x83, 0x6d,
	0xc7, 0xe0, 0xab, 0x63, 0x50, 0x0c, 0x6c, 0xca, 0xe7, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x8b,
	0xee, 0xe5, 0x12, 0x99, 0x01, 0x00, 0x00,
}
